binddn = "cn=admin,dc=example,dc=org"
bindpw = "admin"
host = "ldap://127.0.0.1:389"
base = "dc=example,dc=org"
filter = "(&(objectClass=*)(cn=*))"
attr = "sn"
regex = "^ki"
replacewith = "ka"
checkmode = false

# -- Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }